# Generated by Django 5.0.8 on 2024-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email Address')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('MATH', 'MATH'), ('COMPUTER', 'COMPUTER'), ('PHYSICS', 'PHYSICS')], max_length=20, verbose_name='Department')),
            ],
        ),
    ]
